info:
    name: EasyGlider4

geom:                       ### Geometric parameters ###
    b:   1.8                    # wing span [m]
    c:   0.18523                # mean aerodynamic chord (MAC) [m]
    AR:  10.016                 # aspect ratio [-]
    S:   0.32347                # wing surface area [m2]

inertia:                        ### Mass and inertia parameters ###
    mass: 1.3474                # [kg]
    Ixx:  0.0832              # [kg * m2]
    Iyy:  0.0667               # [kg * m2]
    Izz:  0.1173               # [kg * m2]
    Ixz:  -0.00215             # [kg * m2]

aero:
    e_oswald:   0.9            

    # Static Drag force (D) (total Drag force of aircraft)
    CD0:        0.009           # CD at CL=0 []


aero_aoa:
    ## Angle of attack (AOA)
    # Angle of attack (alpha) -> Lift force (L) (total Lift force of aircraft)
    CL0:        0.629           # CL at aoa = 0
    CLa:        5.35645         # total lift coefficient derivative with respect to AoA [1/rad] 

    # Angle of attack (alpha) -> Pitching moment (m)
    Cm0:        -0.046           # zero AoA pitching moment
    Cma:        -1.11335        # pitching moment coefficient sensitivity wrt AoA [1/rad]
    
aero_ss:
    ## Sideslip
    # Sideslip angle (beta) -> Side force (Y)    
    CYb:       -0.30694         # total side force coefficient [1/rad] (in BRF !!!) #Neglect?

    # Sideslip angle (beta) -> Rolling moment (l)
    Cl0:        0            # rolling moment for symmetric aircraft
    Clb:        -0.09620        # rolling moment sensitivity wrt sideslip angle [1/rad]

    # Sideslip angle (beta) -> Yawing moment (n)
    Cn0:        0             # zero yawing moment for symmetric aircraft []
    Cnb:        0.08616         # yawing moment sensitivity wrt sideslip [1/rad]


    ## Body rates
aero_rate_pitch:
    # Pitchrate (q) -> Lift force (L), Pitching moment (m)
    CLq:         8.36186        # pitch-rate lift coefficient [1/rad] // Etkin and Stengel give different estimation !!! Mainly by tail
    Cmq:        -13.78696       # pitch-rate moment coefficient [1/rad] //Etkin and Stengel give different estimation !!! Mainly by tail

aero_rate_roll:
    # Rollrate (p) -> Side force (Y), Rolling moment (l), Yawing moment (n)
    CYp:        -0.12986        # roll-rate side force coefficient [] #Neglect?
    Clp:        -0.54200        # roll-rate rolling moment coefficient [] //Stengel gives Clp = - (CLa_w / 12) * ((1 + 3*lam)/(1+lam))
    Cnp:        -0.05809        # roll-rate yawing moment coefficient []

aero_rate_yaw:
    # Yawrate (r) -> Side force (Y), Rolling moment (l), Yawing moment (n)
    CYr:        0.23083         # yaw-rate side force effect [] //Etkin gives CYr = CLa_t * (Sf/S) * 2 * (lf/b)
    Clr:        0.11910         # yaw-rate rolling moment effect []
    Cnr:        -0.06791        # yaw-rate yawing moment effect [] //Etkin gives Cnr = -CLa_t * Vf * (2*lf/b)


    ## Aerodynamic effects of control
aero_ctrl_elev:
    # Elevator deflection (de) -> Lift force (L), Pitching moment (m), Drag force (D)
    CLde:        0.27542        # lift sensitivity to elevator deflection [1/rad] (CZde = -0.45)      
    Cmde:        -0.90380       # pitch moment sensitivity wrt elevator deflection [1/rad]

aero_ctrl_ail:
    # Aileron deflection (da) -> Rolling moment (l), Yawing moment (n)
    Clda:        -0.31671       # rolling moment sensitivity wrt Ailerons deflection [1/rad]
    Cnda:        -0.00824       # yawing moment sensitivity wrt Ailerons deflection [1/rad] #jorev: positive roll (left) -> positive yawrate (right)

aero_ctrl_rud:
    # Rudder deflection (dr) -> Side force (Y), Rolling moment (l), Yawing moment (n)
    CYdr:        0.20260         # side force sensitivity to rudder deflection [1/rad] (~ not consistent 0.13208)
    Cldr:        0.01150         # (0.0055)rolling moment sensitivity wrt rudder deflection
    Cndr:        -0.07474       # yawing moment sensitivity wrt rudder deflection [1/rad]

aero_ctrl_thr:
    thr0_to_rpm: 1000
    rpm2_to_static_thrust: 0.000000012
    thr_p1: -0.014700129
    thr_p2: -0.00083119
    thr_c1: 1250
    thr_c2: 64000000
    const_thr: 4.0

actuators:
    TC_thr:      0.15688982
    TC_dE:       0.02 #0.10504226
    TC_dR:       0.02 #0.10504226
    TC_dA:       0.06 #0.17188734


    ### Tether parameters ###
tether:
    teth_rx:     -0.005            # attachment point on aircraft in aircraft body frame X [m]
    teth_ry:          0.0            # attachment point on aircraft in aircraft body frame Y [m]
    teth_rz:          0.05            # attachment point on aircraft in aircraft body frame Z [m]

    teth_length:      120           # tether length
    teth_Ks:          0.66           # spring coefficient
    teth_Kd:          0.44           # damping coefficient

